###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: portabilis-memcached

    mailhog:
      image: mailhog/mailhog:latest
      container_name: portabilis-mailhog
      ports:
        - "8081:8025"

    redis:
      image: redis:alpine
      container_name: portabilis-redis

    postgres:
      image: postgres:9.6-alpine
      container_name: portabilis-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=toor
        - POSTGRES_DB=portabilis

    webserver:
      image: nginx:alpine
      container_name: portabilis-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: portabilis-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

